// /src/modules/client/my-posts/models/my-posts.mock.ts
import type { MyPostItem } from './my-posts.model';

export const MOCK_USER_POSTS: MyPostItem[] = [
  {
    id: 'POST-1080',
    title: 'Cần mua căn hộ 2PN quận 7 ngân sách 2.8 tỷ view thoáng',
    needType: 'BUY',
    propertyType: 'Căn hộ chung cư',
    location: 'Quận 7, TP. Hồ Chí Minh',
    priceRange: '2,8 tỷ',
    areaRange: '65m²',
    createdAt: '09/09/2026',
    updatedAt: '12/09/2026',
    status: 'APPROVED',
    description:
      'Cần mua căn hộ 2 phòng ngủ 2 WC, tầng trung view thoáng mát, có sổ hồng đầy đủ, ưu tiên các dự án Sunrise City hoặc Era Town.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 128,
  },
  {
    id: 'POST-1082',
    title: 'Cần mua gấp đất nền thổ cư TP. Thủ Đức ngân sách 3.5 tỷ',
    needType: 'BUY',
    propertyType: 'Đất thổ cư / Đất nền',
    location: 'Phường Tân Quy, Quận 7, TP. Hồ Chí Minh',
    priceRange: '3,5 tỷ',
    areaRange: '80m²',
    createdAt: '10/09/2026',
    status: 'PENDING',
    description:
      'Cần tìm đất có sổ hồng riêng chính chủ, hẻm từ 4m trở lên, hướng Đông Nam hoặc Nam. Tài chính có sẵn, giao dịch nhanh chóng trong tháng.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 14,
  },
  {
    id: 'POST-1079',
    title: 'Cần thuê nhà xưởng 500m2 khu vực Bình Chánh giá 25tr',
    needType: 'RENT',
    propertyType: 'Kho xưởng / Nhà xưởng',
    location: 'Huyện Bình Chánh, TP. Hồ Chí Minh',
    priceRange: '25 triệu/tháng',
    areaRange: '500m²',
    createdAt: '08/09/2026',
    status: 'REJECTED',
    rejectReason:
      'Nội dung tin đăng thiếu địa chỉ kho cụ thể và số điện thoại liên hệ chưa khớp với dữ liệu đăng ký xác thực tài khoản.',
    description:
      'Cần thuê kho chứa hàng khô, đường xe container ra vào được 24/7, có trạm điện 3 pha.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 5,
  },
  {
    id: 'POST-1072',
    title: 'Cần mua nhà phố mặt tiền đường Nguyễn Thị Thập ngân sách 12 tỷ',
    needType: 'BUY',
    propertyType: 'Nhà phố / Nhà riêng',
    location: 'Đường Nguyễn Thị Thập, Quận 7, TP. Hồ Chí Minh',
    priceRange: '12 tỷ',
    areaRange: '110m²',
    createdAt: '01/09/2026',
    updatedAt: '10/09/2026',
    status: 'HIDDEN',
    description:
      'Tìm nhà phố kinh doanh vị trí đẹp, diện tích ngang tối thiểu 5m, hợp đồng mua bán sang tên ngay. Tạm ẩn do đang thương lượng.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 245,
  },
  {
    id: 'POST-1065',
    title: 'Cần thuê biệt thự sân vườn Thảo Điền Quận 2 ngân sách 70 triệu',
    needType: 'RENT',
    propertyType: 'Biệt thự / Thấu căn',
    location: 'Thảo Điền, Thành phố Thủ Đức, TP. Hồ Chí Minh',
    priceRange: '70 triệu/tháng',
    areaRange: '350m²',
    createdAt: '20/08/2026',
    updatedAt: '05/09/2026',
    status: 'COMPLETED',
    description:
      'Đã chốt xong hợp đồng thuê biệt thự. Đánh dấu hoàn tất nhu cầu.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 312,
  },
  {
    id: 'POST-1050',
    title: 'Cần mua đất công nghiệp Long An diện tích 1ha ngân sách 20 tỷ',
    needType: 'BUY',
    propertyType: 'Đất công nghiệp',
    location: 'Huyện Bến Lức, Tỉnh Long An',
    priceRange: '20 tỷ',
    areaRange: '10,000m²',
    createdAt: '15/07/2026',
    updatedAt: '15/08/2026',
    status: 'EXPIRED',
    description:
      'Tin đăng đã hết thời hạn 30 ngày hiển thị. Cần gửi yêu cầu gia hạn lại.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 189,
  },
  {
    id: 'POST-1088',
    title: 'Cần thuê shophouse khối đế chung cư Quận 4 kinh doanh café',
    needType: 'RENT',
    propertyType: 'Shophouse kinh doanh',
    location: 'Đường Bến Vân Đồn, Quận 4, TP. Hồ Chí Minh',
    priceRange: '45 triệu/tháng',
    areaRange: '90m²',
    createdAt: '15/09/2026',
    status: 'DRAFT',
    description:
      'Bản nháp thông tin thuê shophouse vị trí đẹp lô góc 2 mặt tiền.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 0,
  },
  {
    id: 'POST-1090',
    title: 'Cần mua căn hộ 3PN dự án Vinhomes Central Park Bình Thạnh',
    needType: 'BUY',
    propertyType: 'Căn hộ chung cư',
    location: 'Quận Bình Thạnh, TP. Hồ Chí Minh',
    priceRange: '6,2 tỷ',
    areaRange: '100m²',
    createdAt: '16/09/2026',
    status: 'APPROVED',
    description:
      'Cần tìm mua căn hộ 3 phòng ngủ lầu cao view công viên sông Saigon, sang tên nhanh.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 88,
  },
  {
    id: 'POST-1091',
    title: 'Cần thuê mặt bằng kinh doanh thời trang Nguyễn Trãi Quận 5',
    needType: 'RENT',
    propertyType: 'Mặt bằng kinh doanh',
    location: 'Đường Nguyễn Trãi, Quận 5, TP. Hồ Chí Minh',
    priceRange: '35 triệu/tháng',
    areaRange: '70m²',
    createdAt: '16/09/2026',
    status: 'APPROVED',
    description:
      'Cần thuê mặt bằng tầng trệt lối đi riêng, khu mua sắm sầm uất tuyến phố thời trang.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 42,
  },
  {
    id: 'POST-1092',
    title: 'Cần tìm mua đất vườn nghỉ dưỡng Củ Chi tài chính 1.5 tỷ',
    needType: 'BUY',
    propertyType: 'Đất vườn / Trang trại',
    location: 'Huyện Củ Chi, TP. Hồ Chí Minh',
    priceRange: '1,5 tỷ',
    areaRange: '500m²',
    createdAt: '16/09/2026',
    status: 'PENDING',
    description:
      'Cần mua đất vườn có sắn cây ăn trái, đường ô tô vào tận nơi, pháp lý sổ hồng riêng.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 9,
  },
];
